//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Config/onInputNext.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @OnInputNext: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @OnInputNext()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""onInputNext"",
    ""maps"": [
        {
            ""name"": ""InputNext"",
            ""id"": ""db1eaa28-089f-4844-8d32-16932182901b"",
            ""actions"": [
                {
                    ""name"": ""onInputNext"",
                    ""type"": ""Button"",
                    ""id"": ""d6666185-794a-44b8-8caf-deca75c48037"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dcc90997-0836-457e-8a02-915eb953513d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""onInputNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InputNext
        m_InputNext = asset.FindActionMap("InputNext", throwIfNotFound: true);
        m_InputNext_onInputNext = m_InputNext.FindAction("onInputNext", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InputNext
    private readonly InputActionMap m_InputNext;
    private List<IInputNextActions> m_InputNextActionsCallbackInterfaces = new List<IInputNextActions>();
    private readonly InputAction m_InputNext_onInputNext;
    public struct InputNextActions
    {
        private @OnInputNext m_Wrapper;
        public InputNextActions(@OnInputNext wrapper) { m_Wrapper = wrapper; }
        public InputAction @onInputNext => m_Wrapper.m_InputNext_onInputNext;
        public InputActionMap Get() { return m_Wrapper.m_InputNext; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InputNextActions set) { return set.Get(); }
        public void AddCallbacks(IInputNextActions instance)
        {
            if (instance == null || m_Wrapper.m_InputNextActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InputNextActionsCallbackInterfaces.Add(instance);
            @onInputNext.started += instance.OnOnInputNext;
            @onInputNext.performed += instance.OnOnInputNext;
            @onInputNext.canceled += instance.OnOnInputNext;
        }

        private void UnregisterCallbacks(IInputNextActions instance)
        {
            @onInputNext.started -= instance.OnOnInputNext;
            @onInputNext.performed -= instance.OnOnInputNext;
            @onInputNext.canceled -= instance.OnOnInputNext;
        }

        public void RemoveCallbacks(IInputNextActions instance)
        {
            if (m_Wrapper.m_InputNextActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInputNextActions instance)
        {
            foreach (var item in m_Wrapper.m_InputNextActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InputNextActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InputNextActions @InputNext => new InputNextActions(this);
    public interface IInputNextActions
    {
        void OnOnInputNext(InputAction.CallbackContext context);
    }
}
